/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root";
import { Route as MainRouteImport } from "./pages/_main";
import { Route as NovaAtividadeIndexRouteImport } from "./pages/nova-atividade/index";
import { Route as CursoIndexRouteImport } from "./pages/curso/index";
import { Route as MainIndexRouteImport } from "./pages/_main.index";
import { Route as MainRankingsRouteImport } from "./pages/_main.rankings";
import { Route as MainMedalhasRouteImport } from "./pages/_main.medalhas";
import { Route as CursoAtividadesIndexRouteImport } from "./pages/curso/atividades/index";
import { Route as MainCursosIndexRouteImport } from "./pages/_main.cursos/index";

const MainRoute = MainRouteImport.update({
  id: "/_main",
  getParentRoute: () => rootRouteImport,
} as any);
const NovaAtividadeIndexRoute = NovaAtividadeIndexRouteImport.update({
  id: "/nova-atividade/",
  path: "/nova-atividade/",
  getParentRoute: () => rootRouteImport,
} as any);
const CursoIndexRoute = CursoIndexRouteImport.update({
  id: "/curso/",
  path: "/curso/",
  getParentRoute: () => rootRouteImport,
} as any);
const MainIndexRoute = MainIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MainRoute,
} as any);
const MainRankingsRoute = MainRankingsRouteImport.update({
  id: "/rankings",
  path: "/rankings",
  getParentRoute: () => MainRoute,
} as any);
const MainMedalhasRoute = MainMedalhasRouteImport.update({
  id: "/medalhas",
  path: "/medalhas",
  getParentRoute: () => MainRoute,
} as any);
const CursoAtividadesIndexRoute = CursoAtividadesIndexRouteImport.update({
  id: "/curso/atividades/",
  path: "/curso/atividades/",
  getParentRoute: () => rootRouteImport,
} as any);
const MainCursosIndexRoute = MainCursosIndexRouteImport.update({
  id: "/cursos/",
  path: "/cursos/",
  getParentRoute: () => MainRoute,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof MainIndexRoute;
  "/medalhas": typeof MainMedalhasRoute;
  "/rankings": typeof MainRankingsRoute;
  "/curso/": typeof CursoIndexRoute;
  "/nova-atividade/": typeof NovaAtividadeIndexRoute;
  "/cursos/": typeof MainCursosIndexRoute;
  "/curso/atividades/": typeof CursoAtividadesIndexRoute;
}
export interface FileRoutesByTo {
  "/medalhas": typeof MainMedalhasRoute;
  "/rankings": typeof MainRankingsRoute;
  "/": typeof MainIndexRoute;
  "/curso": typeof CursoIndexRoute;
  "/nova-atividade": typeof NovaAtividadeIndexRoute;
  "/cursos": typeof MainCursosIndexRoute;
  "/curso/atividades": typeof CursoAtividadesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_main": typeof MainRouteWithChildren;
  "/_main/medalhas": typeof MainMedalhasRoute;
  "/_main/rankings": typeof MainRankingsRoute;
  "/_main/": typeof MainIndexRoute;
  "/curso/": typeof CursoIndexRoute;
  "/nova-atividade/": typeof NovaAtividadeIndexRoute;
  "/_main/cursos/": typeof MainCursosIndexRoute;
  "/curso/atividades/": typeof CursoAtividadesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/medalhas"
    | "/rankings"
    | "/curso/"
    | "/nova-atividade/"
    | "/cursos/"
    | "/curso/atividades/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/medalhas"
    | "/rankings"
    | "/"
    | "/curso"
    | "/nova-atividade"
    | "/cursos"
    | "/curso/atividades";
  id:
    | "__root__"
    | "/_main"
    | "/_main/medalhas"
    | "/_main/rankings"
    | "/_main/"
    | "/curso/"
    | "/nova-atividade/"
    | "/_main/cursos/"
    | "/curso/atividades/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren;
  CursoIndexRoute: typeof CursoIndexRoute;
  NovaAtividadeIndexRoute: typeof NovaAtividadeIndexRoute;
  CursoAtividadesIndexRoute: typeof CursoAtividadesIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_main": {
      id: "/_main";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof MainRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/nova-atividade/": {
      id: "/nova-atividade/";
      path: "/nova-atividade";
      fullPath: "/nova-atividade/";
      preLoaderRoute: typeof NovaAtividadeIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/curso/": {
      id: "/curso/";
      path: "/curso";
      fullPath: "/curso/";
      preLoaderRoute: typeof CursoIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_main/": {
      id: "/_main/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof MainIndexRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_main/rankings": {
      id: "/_main/rankings";
      path: "/rankings";
      fullPath: "/rankings";
      preLoaderRoute: typeof MainRankingsRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/_main/medalhas": {
      id: "/_main/medalhas";
      path: "/medalhas";
      fullPath: "/medalhas";
      preLoaderRoute: typeof MainMedalhasRouteImport;
      parentRoute: typeof MainRoute;
    };
    "/curso/atividades/": {
      id: "/curso/atividades/";
      path: "/curso/atividades";
      fullPath: "/curso/atividades/";
      preLoaderRoute: typeof CursoAtividadesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_main/cursos/": {
      id: "/_main/cursos/";
      path: "/cursos";
      fullPath: "/cursos/";
      preLoaderRoute: typeof MainCursosIndexRouteImport;
      parentRoute: typeof MainRoute;
    };
  }
}

interface MainRouteChildren {
  MainMedalhasRoute: typeof MainMedalhasRoute;
  MainRankingsRoute: typeof MainRankingsRoute;
  MainIndexRoute: typeof MainIndexRoute;
  MainCursosIndexRoute: typeof MainCursosIndexRoute;
}

const MainRouteChildren: MainRouteChildren = {
  MainMedalhasRoute: MainMedalhasRoute,
  MainRankingsRoute: MainRankingsRoute,
  MainIndexRoute: MainIndexRoute,
  MainCursosIndexRoute: MainCursosIndexRoute,
};

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  CursoIndexRoute: CursoIndexRoute,
  NovaAtividadeIndexRoute: NovaAtividadeIndexRoute,
  CursoAtividadesIndexRoute: CursoAtividadesIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
