/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./pages/__root";
import { Route as IndexRouteImport } from "./pages/index";
import { Route as RankingsIndexRouteImport } from "./pages/rankings/index";
import { Route as NovaAtividadeIndexRouteImport } from "./pages/nova-atividade/index";
import { Route as MedalhasIndexRouteImport } from "./pages/medalhas/index";
import { Route as CursosIndexRouteImport } from "./pages/cursos/index";
import { Route as CursoIndexRouteImport } from "./pages/curso/index";
import { Route as AtividadesIndexRouteImport } from "./pages/atividades/index";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const RankingsIndexRoute = RankingsIndexRouteImport.update({
  id: "/rankings/",
  path: "/rankings/",
  getParentRoute: () => rootRouteImport,
} as any);
const NovaAtividadeIndexRoute = NovaAtividadeIndexRouteImport.update({
  id: "/nova-atividade/",
  path: "/nova-atividade/",
  getParentRoute: () => rootRouteImport,
} as any);
const MedalhasIndexRoute = MedalhasIndexRouteImport.update({
  id: "/medalhas/",
  path: "/medalhas/",
  getParentRoute: () => rootRouteImport,
} as any);
const CursosIndexRoute = CursosIndexRouteImport.update({
  id: "/cursos/",
  path: "/cursos/",
  getParentRoute: () => rootRouteImport,
} as any);
const CursoIndexRoute = CursoIndexRouteImport.update({
  id: "/curso/",
  path: "/curso/",
  getParentRoute: () => rootRouteImport,
} as any);
const AtividadesIndexRoute = AtividadesIndexRouteImport.update({
  id: "/atividades/",
  path: "/atividades/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/atividades/": typeof AtividadesIndexRoute;
  "/curso/": typeof CursoIndexRoute;
  "/cursos/": typeof CursosIndexRoute;
  "/medalhas/": typeof MedalhasIndexRoute;
  "/nova-atividade/": typeof NovaAtividadeIndexRoute;
  "/rankings/": typeof RankingsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/atividades": typeof AtividadesIndexRoute;
  "/curso": typeof CursoIndexRoute;
  "/cursos": typeof CursosIndexRoute;
  "/medalhas": typeof MedalhasIndexRoute;
  "/nova-atividade": typeof NovaAtividadeIndexRoute;
  "/rankings": typeof RankingsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/atividades/": typeof AtividadesIndexRoute;
  "/curso/": typeof CursoIndexRoute;
  "/cursos/": typeof CursosIndexRoute;
  "/medalhas/": typeof MedalhasIndexRoute;
  "/nova-atividade/": typeof NovaAtividadeIndexRoute;
  "/rankings/": typeof RankingsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/atividades/"
    | "/curso/"
    | "/cursos/"
    | "/medalhas/"
    | "/nova-atividade/"
    | "/rankings/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/atividades"
    | "/curso"
    | "/cursos"
    | "/medalhas"
    | "/nova-atividade"
    | "/rankings";
  id:
    | "__root__"
    | "/"
    | "/atividades/"
    | "/curso/"
    | "/cursos/"
    | "/medalhas/"
    | "/nova-atividade/"
    | "/rankings/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AtividadesIndexRoute: typeof AtividadesIndexRoute;
  CursoIndexRoute: typeof CursoIndexRoute;
  CursosIndexRoute: typeof CursosIndexRoute;
  MedalhasIndexRoute: typeof MedalhasIndexRoute;
  NovaAtividadeIndexRoute: typeof NovaAtividadeIndexRoute;
  RankingsIndexRoute: typeof RankingsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/rankings/": {
      id: "/rankings/";
      path: "/rankings";
      fullPath: "/rankings/";
      preLoaderRoute: typeof RankingsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/nova-atividade/": {
      id: "/nova-atividade/";
      path: "/nova-atividade";
      fullPath: "/nova-atividade/";
      preLoaderRoute: typeof NovaAtividadeIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/medalhas/": {
      id: "/medalhas/";
      path: "/medalhas";
      fullPath: "/medalhas/";
      preLoaderRoute: typeof MedalhasIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/cursos/": {
      id: "/cursos/";
      path: "/cursos";
      fullPath: "/cursos/";
      preLoaderRoute: typeof CursosIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/curso/": {
      id: "/curso/";
      path: "/curso";
      fullPath: "/curso/";
      preLoaderRoute: typeof CursoIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/atividades/": {
      id: "/atividades/";
      path: "/atividades";
      fullPath: "/atividades/";
      preLoaderRoute: typeof AtividadesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtividadesIndexRoute: AtividadesIndexRoute,
  CursoIndexRoute: CursoIndexRoute,
  CursosIndexRoute: CursosIndexRoute,
  MedalhasIndexRoute: MedalhasIndexRoute,
  NovaAtividadeIndexRoute: NovaAtividadeIndexRoute,
  RankingsIndexRoute: RankingsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
